# Generated by Django 3.1.4 on 2020-12-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='arquivo_msg',
            field=models.FileField(null=True, upload_to='data/mensagens'),
        ),
    ]
